### ISSUE TITLE
countries shapefile missing.

### ISSUE THREAD

**Issue by pyAstroDude** [pysal/scipy2019-intermediate-gds#8]
Hi Guys,
First of all, do we have a slack channel for this tutorial. I did not find one but that could be just a mistake on my part. If there is one then please let me know and I can take this discussion over there. Thx.

Now for the issue:
I cloned the tutorial material and made sure all the required packages were installed. Then when I ran the check_environment.py, I got an error saying "Couldn't read countries shapefile.".
When I look in the data directory, I see that it does not contain ne_110m_admin_0_countries.zip file. Is that an oversight?

**Comment by ljwolf** [comment]
Hey, sorry, yes it is. We need to change that to a different dataset.

**Comment by ljwolf** [comment]
This should be resolved now. Let us know if it's not!
